language: python
python:
    - 2.7
    - 3.6
install:
    - pip install coveralls
    - pip install PyYAML
    - pip install pyfakefs
    - pip install -e .
before_script:
    - mkdir logs
script:
    - coverage run unit_tests/runner.py
after_success:
    - coveralls
